# .github/workflows/first-workflow.yml
name: First Workflow

on:
  workflow_dispatch:

env:
  MY_VAR: "Hello from the environment!"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete!"
      - name: Step 2
        run: echo "Step 2 complete and here is the message: $MY_VAR"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Cow says            
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: "Ready for prod–ship it! ${{ env.MY_VAR }}"
          color: magenta
